version: "3.8"
services:
  jekyll:
    build: .
    environment:
      - JEKYLL_ENV=production
    volumes:
      - .:/srv/jekyll
      - /srv/jekyll/vendor/bundle
      - /srv/jekyll/_site
    ports:
      - "4000:4000"
