version: '3'
services:
  jekyll:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    environment:
      - JEKYLL_ENV=production
    command: jekyll serve --host 0.0.0.0 --trace
